src/components/Editor/AddModal.js
src/components/Editor/CreateModal.js
src/components/Editor/RenameModal.js
src/components/SaveDraft.js
src/pages/EditorPage.js

This PR introduces a new editor UI and includes publishing a draft mechanism. The following sources were used as a point of reference:
- Loom Video: [loom](https://www.loom.com/share/25387f1382824e3c83b4887880de4b55)
- Prototype Link: [figma](https://www.figma.com/proto/GS9OJozTJ1PZBkTfJ3V8g5/Near-Social-v2?page-id=989%3A7965&node-id=1008%3A7686&viewport=694%2C-738%2C0.65&scaling=min-zoom&starting-point-node-id=1008%3A7686)
Due to the last minute effort the code is not refactored and the following changes are NOT present in this PR:
- the Saving Data modal has not been modified, as it’s imported from the VM
- due to the above point, the order of buttons in other models hasn't been changed at all (for the sake of consistency)
- Search in Add Component modal is not doable right now - it …

New Editor UI & Publish draft version

---

src/components/navigation/alpha/NavigationButton.js
src/components/navigation/alpha/desktop/DesktopNavigation.js
src/components/navigation/alpha/desktop/UserDropdown.js
src/components/navigation/alpha/desktop/nav_dropdown/NavDropdownMenu.js
src/components/navigation/alpha/desktop/nav_dropdown/NavDropdownMenuLinkList.js
src/components/navigation/alpha/mobile/BottomNavigation.js
src/components/navigation/alpha/mobile/MenuLeft.js
src/components/navigation/alpha/mobile/MenuRight.js
src/data/widgets.js

Ported over `mainnet` components from `calebjacob.near` to [`one.testnet`](https://explorer.testnet.near.org/accounts/one.testnet) on `testnet` so that we can reference correct components depending on environment inside `widgets.js`

fix: Reference components by environment

---

README.md
webpack.config.js

Fix for using `yarn link "near-social-vm"`

Webpack config change to fix `yarn link "near-social-vm"`

---

src/data/widgets.js
src/pages/EditorPage.js
src/pages/EmbedPage.js
src/pages/ViewPage.js

Wraps all viewer pages with our `DS.Theme` component (already published to mainnet and testnet):
https://alpha.near.org/#/adminalpha.near/widget/ComponentDetailsPage?src=adminalpha.near/widget/DS.Theme
https://test.near.social/#/eugenethedream/widget/WidgetSource?src=one.testnet/widget/DS.Theme

Adding DS.Theme wrapper to provide global design system variables

---

package.json
yarn.lock

This might be helpful as a workaround to bottlenecks on getting our PRs to nearsocial/vm merged.  Ideally, we could point only our develop branch to our VM Fork, and leave main pointing to nearsocial/vm for now.

Points near-discovery to a near fork of nearsocial/vm

---

public/index.html
src/App.js
src/hooks/useHashUrlBackwardsCompatibility.js
src/pages/EditorPage.js
src/pages/EmbedPage.js
src/pages/ViewPage.js
vercel.json
webpack.config.js

Adding support for browser history URLs (`/adminalpha.near/widget/...`) while remaining backwards compatible with hash urls (`/#/adminalpha.near/widget/...`).
https://near-discovery-git-feat-browser-h-3c793a-near-developer-console.vercel.app/adminalpha.near/widget/NearOrg.HomePage
https://near-discovery-git-feat-browser-h-3c793a-near-developer-console.vercel.app/#/adminalpha.near/widget/NearOrg.HomePage
This serves two purposes:
- Better SEO support as Google ignores everything after the `#`
- Prettier URLs
- Support element ID anchor scroll: `<a href="#my-html-id">Scroll to element</a>`
Everything appears to be working locally after testing. Will test more on preview URL.
**NOTE: The additions in `vercel.json` are a necessary hack until we switch to Next due to the confusion between file …

Browser History URLs

---

package.json
yarn.lock

Tested locally and the iframe resizer seems to work as expected.
https://near-discovery-git-feat-vm-120-near-developer-console.vercel.app/calebjacob.near/widget/IframeResizerTest

Upgrade to VM 1.2.0 for iframe resizer support

---

public/index.html
src/App.js
src/pages/ViewPage.js
src/zendesk.js

* Add Zendesk support widget snippet
* Capture work in progress exploration
Based on feedback from Alex - intent is to see if we can: 
* Move it up and to the right on mobile 
* Shrink label to (?)
* Reduce opacity
* Grey - reach out to corwin for palette (using 2b2f31 for now based on inspector)
* Hide dynamically? Add an exit button - get rid of it for rest of session - zE.hide(); will do this
* Hide on certain pages? (Scope to only homepage, for example)
* added hide/show functionality for button and repositioning
* updated label
* added functionality to display the support widget on specific pages and when the user is logged in or not
* Pre-fill Account ID and whitespace cleanup
* Remove dup <script> tag
* pulled user name to auto populate help button
* Formatting and logging cleanups …

Prod: add zendesk support widget (#66)

---

src/App.js
src/pages/ViewPage.js

calling `useLayoutEffect` from `App` or `ViewPage` results in inconsistent styling since sometimes the Zendesk widget doesn't become available until after both of those components have finished their initial rendering passes (meaning `useLayoutEffect` wasn't getting called again)
This queues up a check for the existence of the widget every 20ms and, once found, styles it

fix zendesk widget being unstyled sometimes

---

src/components/navigation/org/mobile/MenuLeft.js

fix: Make sure mobile menu close btn width persists

---

src/pages/CreateAccount.js
src/utils/generic.js

- Add validation warning to subtext instead of waiting until attempted submit
- Use updated regex for address validation which does not allow subaccounts or including the TLA

Fastauth: additional address validation

---

src/App.js

Updates mainnet relayer to use https as this is required by the browser when we're viewing near-discovery via https (e.g. not on localhost)

Use https for mainnet relayer

---

src/components/navigation/desktop/DesktopNavigation.tsx
src/components/navigation/mobile/MenuLeft.tsx
src/components/vm/VmInitializer.tsx
src/pages/auth-callback.tsx
src/pages/signin.tsx
src/pages/signup.tsx
src/pages/verify-email.tsx
src/stores/auth.ts
src/utils/auth.js

This PR contains implementation for remembering the page user was at prior to sign in /sign up and redirect back to it when user successfully login. 
Basic flow is that it adds a new param called `redirect` where it holds the url path. Then this param gets passed all the way down to `auth-callback` logic where it redirect to the page if `redirect` param exist. 
During the implementation, I came across strange behaviour where on both sign in / sign up success, it redirects to `signup` page with an error first and then after 5 seconds, it actually completes the login and redirect to the page accordingly. This behaviour existed before this implementation. 
Before sign up:
During sign up:
On sign up success:

ONB-67 Added logic to remember the page before login and redirect back on success

---

src/components/navigation/desktop/DesktopNavigation.tsx
src/components/navigation/mobile/MenuLeft.tsx
src/components/vm/VmInitializer.tsx
src/utils/navigation.ts

This PR contains improved logic on redirect using query param that fixes `redirect` query param stacking issue. 
Also if user's previous pages were either `signin` or `signup` page, it doesn't get passed to query param.

DEC-1218 Bug fix on redirect query param stacking 

---

src/components/navigation/desktop/DesktopNavigation.tsx

This fixes the search URI encoding when making a search and directly pressing `enter` on desktop view. Related PR for fixing it on the widget side too: https://github.com/near/near-discovery-components/pull/112

fix: URI encoding on search pressed for desktop view

---

src/pages/_app.tsx
src/pages/s/[urlShareIndicator].tsx

- Adds new share URL route to that generates meta/og previews for posts and comments
- Post with image: `/s/p?a=nearbrasil.near&b=93679239`
- Comment without image: `/s/c?a=gagdiez.near&b=90024589`
- Removed unnecessary `twitter:image` in `app.tsx` since `og:image` is sufficient
Once this is deployed to production, we should merge this PR: https://github.com/near/near-discovery-components/pull/113
I just realized this won't work in our preview environment due to the testnet/mainnet mismatch since we fetch from `https://api.near.social/get`

Dynamic Meta Preview

---

src/components/MetaTags.tsx
src/pages/_app.tsx
src/pages/s/[urlShareIndicator].tsx

Fixes the latest PR for implementing a share URL. I didn't realize we had duplicate `og:image` tags and crawlers would only respect the first entry (which is our default image). This PR makes sure we only have one set of meta tags on each page.

Fix Share Preview

---

package.json
pnpm-lock.yaml
src/pages/signup.tsx

This PR contains implementation to show a toast when an user with unsupported browser lands on create account page. 
Previously users need to make an action first to see if they can create an account or not. This is a short term UX improvement until we have a proper solution to create FastAuth account on unsupported browser.

Show a toast with info when unsupported browser lands on create account page

---

src/utils/config.ts

mpc-recovery is moving to a different GCP project, this is going to be its new URL

chore: update mpc-recovery mainnet url

---

src/components/vm/VmInitializer.tsx

The example in the initial VM PR has a bug, this is a fix for Viewer.

Fix Link custom element

---

src/hooks/usePageAnalytics.ts
src/utils/rudder-analytics.ts

Rudderstack Page Load events were not consistent with that of Segments. We found the issue to be related to Rudderstack analytics SDK not loading fast enough to fire off the event. 
In this PR, we wait to check if rudder-analytics SDK is ready, if it is not, we push the page Load event into a pendingEvents queue that we flush right after rudder-analytics sdk has been initialized.

Fix: Rudderstack Analytics Page Load Metric

---

src/components/navigation/desktop/UserDropdownMenu.tsx

Removed an extra brace after `kb` in the navigation dropdown menu

fix: withdraw text typo

---

package.json
pnpm-lock.yaml
src/pages/[componentAccountId]/widget/[componentName].tsx

Example for NEAR Horizon:
Note that the preview will be the same for all subpages of a component/app. E.g. the following two will show the same preview
```
https://www.near.org/nearhorizon.near/widget/Index
https://www.near.org/nearhorizon.near/widget/Index?tab=project&accountId=keypom-labs-for-horizon.near
```

generate opengraph previews for components

---

package.json
pnpm-lock.yaml

This PR contains upgrade of `@near-js/biometric-ed25519` package that handles fast-auth on near discovery.
On version `0.3.0` it includes changes that related to this PR (https://github.com/near/near-api-js/pull/1148)
It comes with support on encryption algorithm that browsers from Android devices expects.

Upgrade Fast-Auth package

---

src/components/lib/Toast/Toaster.tsx
src/components/lib/Toast/store.ts
src/components/lib/Toast/styles.ts
src/pages/auth-callback.tsx
src/pages/index.tsx
src/pages/signin.tsx
src/pages/signup.tsx
src/pages/verify-email.tsx
src/utils/auth.js

Implement limited functionality fallback for non webauthn browsers. Users will be able to use discovery up to the point they need to interact with a non socialDB contract.

feat: allow signIn with only LAK for no webauthn browsers

---

src/components/sandbox/Sandbox.js

Fixes the issue of the onboarding screen flashing when forking a component

fix: prevent the onboarding modal from flashing

---

src/pages/_app.tsx

replace direct connection to googletagmanager with rudderstack piping filtered events to gtm

remove google tag manager

---

src/pages/api/search.ts

Closes: https://pagodaplatform.atlassian.net/browse/DEC-1402
After talking with @pkudinov, we agreed that it made sense to implement a proxy endpoint `POST /api/search` that can be used by VM components - this will hide the secrets from the frontend. The "App Store" will be the first feature using this endpoint to support searching for apps.
Inside a VM component, you can access the search endpoint:
```
asyncFetch("/api/search", {
body: JSON.stringify(body),
headers: {
"Content-Type": "application/json",
},
method: "POST",
}).then(...).catch(...);
```
I've already gone ahead and added the new ENV variables to Vercel for all of our gateway environments. Right now there's only a MAINNET indexer, but we can easily update the `beta.near.org` ENV variables to use a `TESTNET` version whenever …

Algolia Search Proxy Endpoint

---

src/utils/analytics.ts

The fix for tracking page tracking accidentally got omitted during a clean up commit. 
This PR adds that logic back. 
You can view more details in the original PR here: https://github.com/near/near-discovery/pull/292

fix: add page tracking fix back

---

src/utils/analytics.ts

It turns out that `new HTMLCollection()` is invalid JavaScript. We just need to handle the case when `element.parentNode` is undefined with an early return.

Fixing getXPath() when parent node does not exist

---

src/components/sandbox/Sandbox.js

Fix forked component state

---

package.json
pnpm-lock.yaml

Update VM version to 2.4.1 from 2.3.2:
- https://github.com/NearSocial/VM/releases/tag/2.4.0
- https://github.com/NearSocial/VM/releases/tag/2.4.1
This includes the following changes:
- Introduce `useState` and `useEffect`. They should work similarly to the React hooks. Example:
```jsx
const [a, setA] = useState(() => {
console.log("Init 'a'");
return "Y";
});
const [b, setB] = useState("B");
const [sum, setSum] = useState(0);
useEffect(() => {
setSum(a.length + b.length);
return () => {
console.log("cleanup");
};
}, [a, b]);
return (
<div>
A = {a}
<br />B = {b}
<br />
Length sum = {sum}
<div>
<button onClick={() => setA((s) => s + "O")}>A</button>
<button onClick={() => setB(b + "O")}>B</button>
</div>
</div>
);
```
- Add `cacheOptions` optional argument to the following methods:
- …

chore: Bump VM version to 2.4.1

---

src/components/navigation/NotificationButton.tsx
src/components/navigation/mobile/MenuLeft.tsx

At this moment when you click on notification button on mobile you'll see a preview with notifications for a while. This is wrong and was discussed [here](https://pagodaplatform.atlassian.net/browse/DEC-1431).
`mobileView` is added is this [PR](https://github.com/near/near-discovery-components/pull/349).

Hide notifications preview on mobile

---

src/components/navigation/desktop/DesktopNavigation.tsx

Closes: https://github.com/near/near-discovery/issues/569
We had some global CSS in the gateway that was overriding nested component CSS.

Fix image display in global search type ahead dropdown

---

next.config.js

redirects to https://pages.near.org/about/network/validators/

fix: broken legacy /validators link

---

src/utils/notifications.ts
src/utils/notificationsLocalStorage.ts

Additional logs and subscriptionError in localStorage.

Debugging service-worker

---

src/pages/index.tsx
src/pages/notifications-settings.tsx
src/pages/notifications.tsx
src/utils/notifications.ts

Closes [#667](https://github.com/near/near-discovery/issues/667)
This PR introduces a note about minimal iOS version for notifications feature. This note depends on iOS device and it's version which means that android users won't see this note. Also if iOS device has it's version > minimal version -> we don't show such note

Add note about minimal required iOS version

---

src/pages/_app.tsx

deleting the inline iubenda config in favor of importing iubenda via google tag manager. this avoids js exceptions

Remove the inline loading of iubenda

---

src/components/NotificationsAlert.tsx
src/hooks/useBosLoaderInitializer.ts
src/hooks/useIosDevice.ts
src/pages/index.tsx
src/pages/notifications-settings.tsx
src/pages/notifications.tsx
src/utils/notifications.ts

Closes: https://github.com/near/near-discovery/issues/684
Our previous logic for detecting the iOS version would return `NaN` due to trying parse a number with multiple periods (EG: `Number("16.2.3")`. In JS, `NaN` is not referentially equal to itself, which was causing an infinite loop when used as a `useEffect()` or `useCallback()` dependency.
I broke out all of the notification alert logic from the home page into `<NotificationsAlert />` to help reduce re-renders of the entire activity page.
I also realized that `useBosLoaderInitializer()` was prematurely setting `hasResolved: true` - which would cause `<VmComponent>` to fetch and render code from the blockchain before using the `redirectMap` provided by BOS Loader for local development.
I could use some help thoroughly testing the …

Fix Notifications Infinite "NaN" Loop

---

src/pages/signup.tsx

Turning auto capitalizing off for email and account id results in improved UX, especially on mobile. Currently while signing up on mobile, the account id input shows an error since the input automatically capitalizes the first letter, which is not a valid account id.

Avoid auto capitalize on FasthAuth sign up page

---

package.json
pnpm-lock.yaml

Release changes: https://github.com/NearSocial/VM/releases/tag/2.5.0
This update introduces `useMemo ` and `useCallback` hooks along with other important additions and fixes

chore: Bump VM version to 2.5.0

---

src/data/bos-components.ts
src/pages/applications.tsx

Related to: https://github.com/near/near-discovery-components/issues/389
I confirmed with @TiffanyGYJ that we should update the `/applications` route now that we've completed the App Library MVP.

Use "App Library" BOS component for /applications page

---

src/components/vm/VmInitializer.tsx
src/utils/analytics.ts

Collect Component Interaction events and send them to Rudderstack. 
This PR requires VM release 2.5.0
It enables this feature documented here: https://github.com/NearSocial/VM/pull/131

Add data component attribute feature

---

package.json
pnpm-lock.yaml

This PR contains bump up the `near-fastauth-wallet` npm package from 0.0.8 to 0.0.9

chore: bump near-fastauth-wallet package

---

.github/workflows/update-sprint-board.yml

I'm not sure whether Selected is actually the same status or if we caused this issue by renaming Selected to Ready for Development. Seems like no harm in adding it.

Move 'Ready for Development' items to next sprint

---

package.json
pnpm-lock.yaml

Related to: https://github.com/near/near-discovery/issues/739
Once we merge this and confirm our dev environment looks good, we'll also want to quickly merge this hotfix: https://github.com/near/near-discovery/pull/768

Upgrading to VM 2.5.2 to support styled("Link")

---

next.config.js
src/hooks/useHashUrlBackwardsCompatibility.ts
src/pages/edit/[...componentSrc].tsx
src/pages/edit/index.tsx

Closes: https://github.com/near/near-discovery-components/issues/458
Turns out that redirects configured in `next.config.js` don't apply to client side routing (they only run when visiting a URL directly - with a full page reload):
> Redirects are not applied to client-side routing (Link, router.push)...
https://nextjs.org/docs/pages/api-reference/next-config-js/redirects
So I set up an explicit page route to handle all redirect edge cases in a single location when redirecting from `/edit/...` to `/sandbox/...`

Fix Edit Redirect

---

src/data/bos-components.ts
src/pages/relayer-demo.tsx

Adding a `/relayer-demo` route that manually sets the relayer URL on mount, and resets the relayer URL on unmount.
The route renders a [BOS component](https://near.org/relayer-demo.near/widget/RelayerMessageDemo) which allows users with FastAuth account + zero balance to add messages to the `guest-book.near` contract.

Add /relayer-demo route

---

src/components/navigation/navigation-categories.ts

We can safely merge this into `develop` now. We'll open another PR to sync `main` tomorrow (on the 8th).

Reveal data availability link in header

---

src/data/web3.ts

dappUrl is required by MetaMask mobile app, otherwise the transactions fails
More info here:
https://github.com/blocknative/web3-onboard/tree/develop/packages/walletconnect

add dappUrl to support MetaMask on mobile

---

src/components/vm/VmInitializer.tsx
src/hooks/useIdOS.ts
src/pages/settings.tsx
src/stores/idosStore.ts

This PR introduces changes for idOS store. From now we're storing the data in localStorage but using zustand which means we have more control on it + clear this store on logout. 
Also this PR introduces smaller changes like refactor idOS methods to get the data and better error handling.
Closes: [#493](https://github.com/near/near-discovery-components/issues/493), [#494](https://github.com/near/near-discovery-components/issues/494)

refactor: Change idOS data storage

---

.idea/prettier.xml
src/pages/[componentAccountId]/widget/[componentName].tsx
src/pages/s/[urlShareIndicator].tsx

From outage thread: https://pagodaplatform.slack.com/archives/C025P00N3QD/p1701264395404659

Temporarily disable api.near.social calls due to outage

---

src/pages/_app.tsx

Fixed issue with zendesk icon on mobile phones. Issue on [link](https://github.com/near/near-discovery-components/issues/392).
Also I had found that when you try to sign in, icon is going over sign in. In this case, that is handled too.

fix: Fixed zendesk icon over modal

---

src/components/vm/VmInitializer.tsx

Some `<Link>` instances define their destination using`to` instead of `href`. This PR handles that case and fixes broken links like communities and activity feed on [DevHub](https://near.org/devhub.near/widget/app)

fix: custom Link element should handle when href is undefined

---

src/pages/signin.tsx

After some investigations, I reviewed the pull request (PR) at https://github.com/near/near-discovery/pull/903
which appears to be the cause of session loss and sign-out when refreshing the page.
To address this issue, I propose a set of changes that will fix the issue: https://github.com/near/near-discovery/issues/910.
- Added checks `walletSelectorState` and `fastAuthWallet`.

Fix: Session lost with MyNearWallet

---

next.config.js

adds a referrer policy to capture same-origin referrer & removes a unnecessary header
closes [#884](https://github.com/near/near-discovery/issues/884)

set a referrer policy header

---

next.config.js

Will need to look into a work around to support sending same origin referrer headers without breaking [social ipfs images](https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/Image)

fix(headers): temporarily remove to fix issues resolving ipfs images

---

next.config.js

The previous attempt coupled two referrer policies in one array value declaration, causing an error. We actually only need to specify this one value to ensure that the referring origin is passed to cross-domain requests and the entire path passed for same-origin.

Specifies a referrer policy to ensure we pass the referrer to analytics

---

src/components/navigation/navigation-categories.ts

Updates github link on near.org to point to GH org's README. DX content has been migrated there :)

fix: update github link to point to org readme

---

next.config.js

with the recent /papers rebuild we lost a direct route to /papers/nightshade

route to /papers/nightshade

---

src/pages/sitemap.xml.tsx

Sitemap threw error with blankspace
Removing blankspace shows proper sitemap

chore: remove blankspace sitemap.xml.tsx

---

next.config.js
src/components/navigation/navigation-categories.ts
src/data/bos-components.ts
src/pages/_app.tsx
src/pages/founders.tsx
src/utils/zendesk.ts

Closes: #974 
[Demo](https://www.loom.com/share/d2db90ba0afa4e4793f29b3887f2924b?sid=02d35900-2f54-4da5-825d-79a76759caf5)

feat: update route to founders page

---

package.json
pnpm-lock.yaml

closes [919](https://github.com/near/near-discovery/issues/919)

update to the vm release 2.6.0

---

src/data/bos-components.ts
src/pages/[...arbitrary].tsx
src/pages/events.tsx
src/utils/config.ts
src/utils/events.ts

feat: create new events page

---

next.config.js
src/pages/[componentAccountId]/widget/[componentName].tsx
src/pages/applications.tsx

Building upon [this pr](https://github.com/near/near-discovery/pull/1017), this updates the remaining signin flows to use the new auth modal 
closes https://github.com/near/near-discovery/issues/970

route existing sign in/up links to overlay the new auth modal on the applications page

---

src/middleware.ts
src/pages/geoBlocked.tsx
src/utils/analytics.ts

- adds a new 1st party cookie, user-country-code
- prevents near.org access for users from restricted areas 
- includes userCountryCode in product analytics for opted-in users.
closes https://github.com/near/near-discovery/issues/1022

geo boundary config for restricted areas

---

src/pages/[componentAccountId]/widget/[componentName].tsx
src/pages/applications.tsx

1. visit near.org preview link
2. connect wallet
3. visit preview-link/signin
4. visit preview-link/signup
5. You remain logged in and the auth modal should not reappear

fix: avoid triggering the sign-in modal if user has already authenticated

---

src/components/lib/Text/Text.tsx
src/components/near-org/ComponentWrapperPage.tsx
src/components/sidebar-navigation/PinnedApps.tsx
src/components/sidebar-navigation/Sidebar.tsx
src/components/sidebar-navigation/SmallScreenHeader.tsx
src/components/sidebar-navigation/store.ts
src/components/sidebar-navigation/styles.ts
src/components/sidebar-navigation/utils.ts
src/components/vm/VmInitializer.tsx
src/hooks/useGatewayEvents.ts
src/pages/[componentAccountId]/widget/[componentName].tsx
src/pages/embed/[accountId]/widget/[componentName].tsx
src/pages/index.tsx
src/pages/s/[urlShareIndicator].tsx
src/styles/globals.css

Closes: https://github.com/near/near-discovery/issues/1056
- Implement pinned apps in the new sidebar layout. Since our sidebar layout is still not enabled, you'll need to test the preview link by adding `?sidebar=true` to the end of your URL. The pinned UI on the `ComponentDetailsPage` and `ProfilePage` will only be visible if the sidebar layout is enabled.
- Implement  generic hook and pattern for passing events and data between the gateway and BOS components via `useGatewayEvents()`. This allows our trusted BOS components to emit an event to the gateway when an app is pinned or unpinned. This allows us to update the sidebar UI optimistically as soon as a user clicks on pin or unpin.
- When pinned apps are loaded or modified, they are cached in `localStorage` to provide an instant …

Pinned Apps (2 of 2)

---

src/components/sidebar-navigation/hooks.ts

I made a change recently to simplify `?sidebar=true`, but didn't realize it introduced a new issue with the feature reverting after clicking on a link. This fixes that.

Fix ?sidebar=true test flag

---

src/pages/s/[urlShareIndicator].tsx

Closes: [1094](https://github.com/near/near-discovery/issues/1094)

feat: create metadata handler for blogposts

---

.github/workflows/continuous-integration-workflow.yml

Our `pnpm install` and `prettier` CI actions were set to use the latest version of `pnpm`. This PR fixes the failures that our lockfile has with version 9+ of pnpm.

chore: set pnpm version for CI to 8.5.1

---

.husky/pre-commit
src/pages/s/[urlShareIndicator].tsx

Seems like we didn't use `pnpm lint` along with `pre-commit` script. That's why some warnings could be missed. This PR introduces changes to `pre-commit` script to make sure our project aligned with our prettier and linter rules

chore: update commit script

---

package.json
pnpm-lock.yaml

This PR introduces updates of `@commitlint` module. As per their [documentation](https://commitlint.js.org/guides/local-setup.html#test-simple-usage) this seems to work well:

chore: update `commitlint` module

---

src/data/bos-components.ts

Fixed `Blog.Feed` reference under testnet settings

Fix component reference on testnet

---

src/components/layouts/DefaultLayout.tsx
src/components/sidebar-navigation/DiscoverDrawer.tsx
src/components/sidebar-navigation/MarketingDrawer.tsx
src/components/sidebar-navigation/Sidebar.tsx
src/components/sidebar-navigation/sections.ts
src/components/sidebar-navigation/styles.ts
src/pages/index.tsx

This PR enables logged in gateway view as a logged out view (other words makes this view by default). At this moment, this view enabled via `NEXT_PUBLIC_SIDEBAR_LAYOUT` env variable.
Closes https://github.com/near/near-discovery/issues/1145

feat: enable new homepage

---

src/pages/bosblog/index.tsx

Closes: https://github.com/near/near-discovery-components/issues/793
Part 1: https://github.com/near/near-discovery-components/pull/808

Conditionally render NearOrg.Footer on BlogPostPage (2 of 2)

---

src/pages/bosblog/index.tsx

Closes: [Blog.Feed](https://github.com/orgs/near/projects/92/views/6?pane=issue&itemId=61052380) Allowing for a gateway to set the url for its blog component.

feat: allow for gateway to pass in url for bosblog component

---

src/components/sidebar-navigation/MarketingDrawer.tsx

a somewhat clunky workaround for dev.near.org to provide quick access to view the details of the currently in view BOS component since the following onhover menu option is not part of this UI. 
That implementation would show & hide that menu based on the user's onhover action, was was a convenient rerender hook that we used to check if the current view contained a bos component. The new menu is more static, and the result in this workaround is that the  More -> Develop menu's `Inspect Component` option may appear event when a non-bos component is in view like [dev.near.org/sandbox](https://dev.near.org/sandbox)

adds a 'View Component' alternative for dev.near.org

---

.env.example
src/pages/settings.tsx
src/utils/config.ts

This PR introduces a new environment variable called `NEXT_PUBLIC_IDOS_CREATE_ACCOUNT_URL` to have an opportunity to change the idos create account url in a few seconds (if needed)
Part 1: https://github.com/near/near-discovery-components/pull/821

chore: add idos create account link (2 of 2)

---

src/pages/blog/[[...pages]].tsx

This is in support of verifying the Blog UI as part of the streamlined process to sync blogs from wordpress to near.org/blog as described [here](https://github.com/near/nearorg_wordpress_marketing/blob/develop/README.md)

Support testing blog content by toggling the github branch used for blog content based on the current environment

---

src/components/layouts/DefaultLayout.tsx
src/components/sidebar-navigation/LargeScreenHeader.tsx
src/components/sidebar-navigation/LargeScreenProfileDropdown.tsx
src/components/sidebar-navigation/Search.tsx
src/components/sidebar-navigation/Sidebar.tsx
src/components/sidebar-navigation/SmallScreenHeader.tsx
src/components/sidebar-navigation/styles.ts

Like I said in this [PR](https://github.com/near/near-discovery-components/pull/836), we decided to 
> Bring the top navbar back along with search (this is the part 2 on the near-discovery side);
In this PR I brought top bar back along with ProfileDropdown.
Relates to https://github.com/near/near-discovery/issues/1196.
Feel free to ask any questions you have!

chore: reduce amount of search categories (Part 2/2)

---

.env.example
package.json
pnpm-lock.yaml
src/components/vm/VmInitializer.tsx
src/hooks/useGatewayEvents.ts
src/pages/_app.tsx
src/pages/documentation/[[...slug]].tsx
src/utils/config.ts

Closes: https://github.com/near/near-discovery/issues/1223
Removed existing Zendesk widget and added Gleap support widget to `dev.near.org`. We'll need to update the background image in the Gleap dashboard - left a comment here: https://github.com/near/near-discovery/issues/1223#issuecomment-2214816050
Environment variables have been set in Vercel.

Remove Zendesk widget in favor of Gleap (2 of 2)

---

package.json
pnpm-lock.yaml

Closes: https://github.com/near/fast-auth-signer/issues/249
Temporarily use VM fork to test out FastAuth signAndSendDelegateAction() changes until official PR is merged: https://github.com/NearSocial/VM/pull/200

FastAuth VM Support

---

src/components/research-form-wizard/FormPages/Experience.tsx
src/components/research-form-wizard/FormPages/FollowUp.tsx
src/components/research-form-wizard/FormPages/Motivation.tsx
src/components/research-form-wizard/FormPages/UserType.tsx
src/components/research-form-wizard/ResearchFormWizard.tsx
src/components/research-form-wizard/StepLayout.tsx

PR address issues in the developer survery:
- ensuring the next button is visible/scrollable when the other input box is displayed 
- flatten ruddstack messages
- enable submit button on 'no thanks' selection
Closes #1258

fix: adjust styles for form to scroll on select other on motivation page

---

src/utils/catalogSearchApi.ts

The nearcatalog.xyz redesign moved their search endpoint to a new URL.

fix: update nearcatalog url

---

src/pages/applications.tsx

Since NEAR Catalog, the BOS component behind the Applications page (https://dev.near.org/applications), is migrating to a new version (https://nearcatalog.xyz/) built with React, we need to update the BOS component source code with an embedded iframe that renders the https://nearcatalog.xyz/ page inside the component. 
To make sure the URL query parameters are updated properly after clicking links inside the iframe, we'd like to expose the `setURLSearchParams` function to the `nearcatalog.near/widget/Index` component. For example, when user clicks on Ref Finance project, the URL should be updated to `https://dev.near.org/application?id=ref-finance`. But BOS VM doesn't allow updating URL query parameters programmatically, so we propose to add an additional function at gateway level.
For …

Expose `setURLSearchParams` and `scrollTo` functions to Applications page (NEAR Catalog component)

---

src/pages/applications.tsx

As mentioned in PR #1301, we'd like to update URL query parameters from NEAR Catalog component. 
But we cannot read the URL query parameters as `props` in NEAR Catalog component under the `applications` router. This PR fixes this issue.

fix: import router query as component props in applications page

---

src/components/wallet-utilities/KeyTable.tsx

fix: broken styles for firefox in wallet utilities

---

src/components/home/Contracts/index.tsx
src/components/home/DecentralizedApps/index.tsx

This pull request includes several style adjustments to the `Contracts` and `DecentralizedApps` components in the `src/components/home` directory. The changes primarily involve modifying the height and width properties to ensure consistent layout and appearance.

fix: styles issue on home page for Safari 17

---

src/pages/privacy.tsx

This pull request adds a static Privacy Policy page to the website. The content is based on a snapshot from the Wayback Machine to ensure consistency and accuracy. The new privacy.tsx page includes all necessary information and follows the existing styling guidelines.

Add static Privacy Policy page
