near/near-discovery

- src/components/navigation/alpha/desktop/DesktopNavigation.js
- src/components/navigation/alpha/icons/Return.js
Add return icon when search input is focused to indicate that enter can be pressed to execute a search
> feat: Add return icon to search input

- src/data/links.js
Updated tutorial url for Josh: https://pagodaplatform.slack.com/archives/C04QKBVV7DF/p1677698963507409
Merging straight to `main` as a hotfix and then we'll sync backwards to `develop`.
> Updated Tutorial URL

- src/components/navigation/alpha/mobile/MenuLeft.js
> Fix: tutorials typo on mobile

- src/data/widgets.js
I added `DIG.Theme` and `DIG.Button` to both mainnet and testnet.
> Use `DIG.Theme` instead of `DS.Theme`

- src/App.js
- src/pages/FlagsPage.js
- src/pages/ViewPage.js
- src/utils/flags.js
Flags Page (must navigate to `/flags` manually)
Banner which displays when using BOS Loader either via flags or local viewer `.env`
> Add flags page with support for bos loader url

- src/App.js
- src/components/navigation/org/wrapper/desktop/main_navigation_menu/MainNavigationMenu.js
- src/data/widgets.js
Add NEAR Horizon navigation in navbar and add link to widget to show on /horizon route.
> feat: Add NEAR Horizon navigation/routing

- src/App.js
- src/components/navigation/org/mobile/AccordionMenu.js
- src/components/navigation/org/mobile/MenuLeft.js
- src/components/navigation/org/mobile/TopNavigation.js
- src/components/navigation/org/orgLinks.js
- src/components/navigation/org/wrapper/desktop/DesktopNavigation.js
- src/components/navigation/org/wrapper/desktop/main_navigation_menu/MainNavigationMenu.js
- src/data/widgets.js
In follow up PR: Longer descriptions for each nav link (when available)
> fix: Use correct nav link data

- src/App.js
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1137
> Update meta tags for homepage, use and ecosystem

- src/hooks/useRedirectMap.js
- src/pages/ViewPage.js
getting this up for additions to new areas, we can refactor existing duplicate code later
> add hook for bos-loader redirectMap

- src/components/navigation/org/mobile/TopNavigation.js
- src/components/navigation/org/wrapper/desktop/DesktopNavigation.js
https://pagodaplatform.atlassian.net/browse/DEC-1141
> fix: re-org mobile navigation

- src/components/navigation/org/mobile/AccordionMenu.js
- src/components/navigation/org/orgLinks.js
- src/components/navigation/org/wrapper/desktop/main_navigation_menu/MainNavigationMenu.js
https://pagodaplatform.atlassian.net/browse/DEC-1150
> Nav link updates

- src/components/navigation/org/orgLinks.js
- Updated docs link from /`discovery` -> `/bos`
- Updated quickstart from docs to onboarding wizard
> update docs & quickstart links

- src/data/widgets.js
Relates to this PR:  https://github.com/near/near-discovery-components/pull/84;
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1111;
DO NOT MERGE until this PR is not merged https://github.com/near/near-discovery-components/pull/84
> Change src of `widgetMetadataEditor` for mainnet

- src/pages/CreateAccount.js
- src/utils/generic.js
**Description:**
This PR introduces input validation for email and account ID, as well as an improved method of generating account IDs from email addresses.
**Changes:**
- Added `ErrorText` styled component for displaying input validation error messages
- Updated `CreateAccount.js` to use `react-hook-form` validation for email and account ID inputs
- Added a regex pattern to validate email addresses and account IDs
- Modified `getEmailId` function in `generic.js` to transform email addresses to valid account IDs by converting to lowercase and replacing invalid characters with a hyphen
- Updated `isValidEmail` function to use the `emailPattern` constant
**Co-authored by:**
- CALEB JACOB <thecalebjacob@gmail.com>
> Fastauth Form Validation + Address Generation

- src/pages/CreateAccount.js
This PR optimizes and simplifies the account validation process in the `CreateAccount.js` file. The changes include:
- Adding a `clearErrors` function to the `useForm` hook to clear validation errors for the username and email fields.
- Updating the validation check for the username field to include the account availability status.
- Refactoring the account status message and state handling, eliminating unnecessary conditional checks.
- Improving the styling of the account status message by adding appropriate colors for error and success states.
> condense account validation

- src/pages/signin.tsx
> redirect to home route upon sign in from /signin

- src/pages/signup.tsx
This PR contains redirect logic on sign up page. 
(Same logic has been implemented on sign in page but missing on sign up)
> Implement redirect logic on sign up page

- src/components/navigation/desktop/DesktopNavigation.tsx
- src/components/navigation/mobile/TopNavigation.tsx
- src/pages/signup.tsx
Added "Create Account" CTA in main sticky nav for mobile:
> Mobile: Create Account CTA

- src/components/BosLoaderBanner.tsx
- src/components/lib/Button/Button.tsx
- src/components/lib/Button/index.tsx
- src/components/lib/Text/Text.tsx
- src/components/lib/Text/index.tsx
- src/components/lib/Toast/styles.ts
- src/hooks/useFlags.ts
- src/pages/flags.tsx
- Improved layout
- Switched form to use `react-hook-form` to better support validations and other flags in the future
- Using toast to notify on flags update instead of `alert`
> Improved Flags Page

- next.config.js
closes https://pagodaplatform.atlassian.net/browse/DEC-1262
> Marketing redirect URL

- src/pages/[componentAccountId]/widget/[componentName].tsx
- src/pages/_app.tsx
- src/utils/zendesk.ts
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1217
> Fix styling of zendesk component

- src/components/near-org/ComponentWrapperPage.tsx
- src/components/near-org/NearOrg.Ecosystem.CommunityPage.jsx
- src/components/near-org/NearOrg.Ecosystem.GetFundingPage.jsx
- src/components/near-org/NearOrg.Ecosystem.OverviewPage.jsx
- src/components/near-org/NearOrg.Ecosystem.WorkAndEarnPage.jsx
- src/components/near-org/NearOrg.HomePage.jsx
- src/components/near-org/NearOrg.UsePage.jsx
- src/utils/analytics.ts
- Record click events on all pages
- Pass along `xpath` value to identify unique elements
> Unique events via xpath

- src/pages/auth-callback.tsx
It’s a simple fix that will work on the server, but the problem is with `useEffect` in `auth-callback.tsx` and it will still not work in local env with strict mode enabled.
> Fast auth fix

- src/pages/[componentAccountId]/widget/[componentName].tsx
- src/pages/_app.tsx
- src/styles/globals.css
- src/utils/zendesk.ts
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1304
The thing is we have a Zendesk widget whose location logic is broken on develop branch (it's visible all the time and not only for logged in users and on the home page).
> Fix Zendesk location

- src/components/navigation/mobile/TopNavigation.tsx
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1317
> Fix near logo location on mobile

- .idea/.gitignore
- .idea/jsLibraryMappings.xml
- .idea/modules.xml
- .idea/near-discovery.iml
- .idea/prettier.xml
- .idea/vcs.xml
- src/lib/selector/wallet.js
- Updated appropriate function signature.  This would've been caught if we were using types in the file, so proper mitigation here is to also have this file converted to TS, which we'll get scheduled for next sprint.
- Added configuration for Webstorm or other idea IDEs to auto-run prettier on save
> Resolve multiple transactions failure for FastAuth accounts

- next.config.js
- package.json
- src/pages/_app.tsx
- src/utils/analytics.ts
- src/utils/rudder-analytics.ts
- src/utils/segment-analytics.ts
- tsconfig.json
- types/rudderstack-analytics.ts
Enables Rudderstack Analytics SDK for Near.org. 
Segment Analytics SDK will be utilized in parallel with Rudderstack for a brief migration window.
> DATA-75 feat: Rudderstack Analytics

- src/utils/rudder-analytics.ts
> chore: update prod rudderstack key

- src/pages/auth-callback.tsx
resolves https://pagodaplatform.atlassian.net/browse/DEC-1294
> prevent auth-callback effect from firing on each component render

- src/components/navigation/Navigation.tsx
- src/components/navigation/desktop/DesktopNavigation.tsx
- src/components/sandbox/Mobile/MobileBlocker.js
Closes: https://pagodaplatform.atlassian.net/browse/DEC-1318
Relates to: https://github.com/near/near-discovery-components/pull/131
> Change desktop minimal width

- package.json
- pnpm-lock.yaml
Adds fixes to trial account sign in to support custom IPFS CIDs
> minor bump to keypom package

- .github/workflows/promote-develop-to-main.yml
help us ensure a consistent release cadence with auto generated PRs to promote develop to main
> github action for develop -> main PRs

- src/components/lib/Button/Button.tsx
Refactored `lib/Button` to hoist `styled()` outside of function scope. I did a lot of manual testing after the refactor and everything looked good.
> Refactor Button

- src/components/sandbox/Sandbox.js
Reverts near/near-discovery#320
> Revert "fix: prevent the onboarding modal from flashing"

- src/components/banners/NearconBanner.tsx
Relates to: https://pagodaplatform.atlassian.net/browse/DEC-1383
> DEC-1380: Hide nearcon banner on it's own page

- src/components/banners/NearconBanner.tsx
> Hide nearcon banner on it's own page (#334)

- src/hooks/useBanner.ts
> Fix visibility of nearcon banner

- src/utils/analytics.ts
Uses the correct write key for prod events in rudderstack
https://github.com/near/near-discovery/pull/282/files
> fix: update rudder stack key

- src/pages/_app.tsx
- src/utils/notifications.ts
- src/utils/notificationsHelpers.ts
- src/utils/notificationsLocalStorage.ts
This is a set of functions to store users' decisions and current browser settings in local storage.
> Notifications - store push notification data in local storage

- public/service-worker.js
- src/data/bos-components.ts
- src/pages/index.tsx
`const applicationServerKey = 'BCZN5uqYMBZ2VCV3y0F0emodyYRGyt5JTgfIIzYVXIHKSBwuG0kb0NpPA-DM4nfmfRFiFu-MpKS2eNG7bhxQWn0';`
Can be used for testing subscribing to push notifications.
Also, this version of the modal component needs to be used:
https://github.com/near/near-discovery-components/pull/324
> Notifications - show Notifications Alert with basic conditions

- src/pages/index.tsx
- src/utils/types.ts
Blocked by: https://github.com/near/near-discovery-components/pull/333.
Closes:
- https://pagodaplatform.atlassian.net/browse/DEC-1458;
- https://pagodaplatform.atlassian.net/browse/DEC-1459;
- #373 
- #372
> Show notiication modal for new users

- src/pages/index.tsx
- src/utils/types.ts
Reverts near/near-discovery#551
> Revert "Show notiication modal for new users"

- src/pages/index.tsx
- src/utils/types.ts
- Show notiication modal for new users
- Show notiication modal for existing users
> dec 1458 show notification modal for new users

- src/pages/index.tsx
- src/utils/notificationsLocalStorage.ts
closes https://github.com/near/near-discovery/issues/605
> Notifications - improve local storage

- public/site.webmanifest
- src/pages/_app.tsx
- src/pages/index.tsx
- src/utils/notifications.ts
- src/utils/notificationsLocalStorage.ts
Fell free to change the manifest texts. 
We also need to add the icons.
> Notifications iOS

- package.json
- pnpm-lock.yaml
Release changes: https://github.com/NearSocial/VM/releases/tag/2.4.2
> chore: Bump VM version to 2.4.2

- src/utils/notifications.ts
Please, test this branch before merging.
> Update notifications-server domain

- src/data/bos-components.ts
- src/pages/index.tsx
- src/utils/notifications.ts
Closes #604
Related to [#367](https://github.com/near/near-discovery-components/pull/367)
[Loom video](https://www.loom.com/share/11fc20ec8e064f49b69a75ef76cda257?sid=4ca31428-3a36-4644-b624-0cf507c486c8)
Do not merge before:
> Prepare functionality to show `HomeScreenAlert` for iOS devices

- src/pages/_app.tsx
adds an iubenda cookie prompt (iubenda creds in 1password) with automatic rejection of 3rd party cookies
> cookie prompt

- src/components/navigation/CurrentComponent.tsx
- src/components/navigation/Navigation.tsx
- src/components/navigation/desktop/DesktopNavigation.tsx
- src/components/navigation/desktop/MainNavigationMenu.tsx
- src/components/navigation/mobile/AccordionMenu.tsx
- src/components/navigation/navigation-categories.ts
Closes: https://github.com/near/near-discovery/issues/677
Closes: https://github.com/near/near-discovery/issues/669
Closes: https://github.com/near/near-discovery/issues/671
Note: the current NEAR Org pages on this preview build aren't using BOS components, so you won't see `Current Component` in the `Develop` nav. Go to a route like `/people` or `/near/widget/DIG.OverviewPage` to see it show up.
> Header UX Updates

- src/components/navigation/navigation-categories.ts
> Update news link in nav

- next.config.js
closes https://github.com/near/near-discovery/issues/709
> chore: add redirect from component to nearcon app

- .github/release.yml
- .github/workflows/prs_must_have_labels.yml
Adds a config file for auto-generated release notes based on tags added to PRs
Use one of these tags on your PRs to categorize in the change log. PRs without tags, or with tags that do not match this list, will be added as general enhancements.
- bug
- feature
- breaking-change
- dependency
- enhancement
> Support auto generated changelogs

- src/components/navigation/Navigation.tsx
- src/components/navigation/desktop/MainNavigationMenu.tsx
- src/components/navigation/navigation-categories.ts
- src/data/bos-components.ts
- src/pages/blockchain.tsx
- src/pages/data-availability.tsx
- src/pages/data-infrastructure.tsx
- src/pages/fast-auth-and-relayers.tsx
- src/pages/open-web-applications.tsx
Closes: https://github.com/near/near-discovery/issues/712
This PR should only be merged after Part 1 is merged: https://github.com/near/near-discovery-components/pull/476
We needed to add a new `Platform` main nav section - so I had to update our breakpoints to accommodate the wider nav.
> NEAR Org Landing Pages (Part 2 of 2)

- package.json
- pnpm-lock.yaml
- src/components/vm/VmInitializer.tsx
Fixes https://github.com/near/near-discovery/issues/781
Here is a preview of ledger in wallet-selector for near.org:
> Added Ledger to wallet selector

- package.json
- pnpm-lock.yaml
Upgading `near-fastauth-wallet` as it has a slightly improved mobile UI
> Upgrade fast auth

- src/components/navigation/desktop/TypeAheadDropdown.tsx
Fixes https://github.com/near/near-discovery/issues/807 .
This PR is related with: https://github.com/near/near-discovery-components/pull/521
> Passed closeSearch function to close search UI

- .github/ISSUE_TEMPLATE/epic.md
Hey @charleslavon ! Thanks for [kicking off this conversation](https://pagodaplatform.slack.com/archives/C066704H02C/p1699902249101599) and asking for feedback on the new template. 
Here I've taken your format and grouped it into three buckets:
- What?
- Why?
- How?
My brain finds it easier to digest the information when grouped into these categories and curious if you or others feel the same.
> [WIP] epic template suggestions

- src/components/sandbox/Navigation/NavigationRight.js
- src/components/sandbox/Sandbox.js
This PR introduces saving a fork source data for a widget that is published within a sandbox. Related issue: https://github.com/near/near-discovery/issues/341
> Save fork data

- src/pages/[componentAccountId]/widget/[componentName].tsx
- src/pages/s/[urlShareIndicator].tsx
port hotfix to develop in the form of try/catch around getServerProp fns
> port hotfix to develop

- src/components/banner/Horizon.tsx
- src/components/navigation/desktop/DesktopNavigation.tsx
- src/components/navigation/mobile/Menu.tsx
- src/hooks/useBanner.ts
Adds a banner to the homepage to highlight the horizon accelerator program.
> horizon accelerator banner

- src/components/vm/VmInitializer.tsx
to ensure both href and to attributes are properly validated
> refactor custom link component

- package.json
- pnpm-lock.yaml
- src/pages/settings.tsx
- src/stores/idosStore.ts
This PR introduces the new version of idos-sdk along with code cleanup
Closes #865 
Related to https://github.com/near/near-discovery-components/pull/607
> chore: update `idos-sdk` version to `0.0.30`

- src/components/vm/VmInitializer.tsx
- src/pages/settings.tsx
Relates to https://github.com/near/near-discovery-components/pull/607
> fix: fetch data from idOS

- src/index.d.ts
- src/utils/analytics.ts
as a workaround for chrome's default to reduced user-agent data
> chore(data): send user agent detail with anonymous usage data

- src/components/sandbox/Sandbox.js
- src/components/sandbox/TabProps/index.js
- src/components/vm/VmInitializer.tsx
- src/hooks/useBosLoaderInitializer.ts
- src/hooks/useIdOS.ts
- src/pages/settings.tsx
- src/pages/signup.tsx
- src/utils/analytics.ts
- src/utils/notifications.ts
> adding events to report on caught errors

- src/components/vm/VmInitializer.tsx
Depends upon https://github.com/NearSocial/VM/pull/175
closes https://github.com/near/near-discovery/issues/919
> Vm error callback

- .github/workflows/promote-develop-to-main.yml
- next.config.js
this is a top google result when searching: near nightshade
> fix near.org/papers/nightshade

- next.config.js
> setup a homepage for ETHDenver

- .gitignore
- package.json
- pnpm-lock.yaml
- src/components/vm/VmInitializer.tsx
- src/hooks/useSignInRedirect.ts
Reverts near/near-discovery#929
> Revert "Put fast-auth-signer in iframe for authentication process."

- package.json
- pnpm-lock.yaml
- src/utils/events.ts
Currently we display all the events but there is no need to show passed events, so this PR introduces the new query param to fetch some.
Also, I've added a `moment` library to easily format the date
> fix: show fresh events

- next.config.js
Relates to https://github.com/near/near-discovery/pull/1032
> hotfix: show file documents on standalone pages

- src/pages/_app.tsx
We want to fix the canonical link reference for SEO
See this issue for more details:
https://github.com/near/near-discovery/issues/1029
> fix: Update canonical reference link on _app.tsx

- src/components/navigation/NotificationButton.tsx
> chore: remove unnecessary wrapper from `NotificationButton`

- src/components/sidebar-navigation/styles.ts
- src/styles/globals.css
Fixing a few minor style issues that popped after further testing of the new sidebar layout.
> Minor CSS Sidebar Fixes

- src/components/banner/Horizon.tsx
- src/components/lib/Button/Button.tsx
- src/components/marketing-navigation/desktop/DesktopNavigation.tsx
- src/components/marketing-navigation/mobile/MobileNavigation.tsx
Related to https://github.com/near/near-discovery/issues/1075
> feat: add new Horizon banner

- src/pages/bosblog/index.tsx
This is the gateway companion PR that is required for https://github.com/near/near-discovery-components/pull/704 to be functional.
> fix: update blog to pass in contributors

- src/pages/index.tsx
Partially Implements: https://github.com/near/near-discovery/issues/1060
We should merge this before the other PR I'll need to open on the components PR. I'll set this to auto merge.
> Sync Home Page Events (1/2)

- src/components/layouts/DefaultLayout.tsx
- src/components/sidebar-navigation/hooks.ts
- src/data/bos-components.ts
- src/pages/index.tsx
Closes https://github.com/near/near-discovery/issues/1090
> feat: make new home page visible along with sidebar

- .github/release.yml
- .github/workflows/prs_must_have_labels.yml
- src/components/marketing-navigation/categories.ts
> adds a nav item to infra's zendesk support

- src/components/marketing-navigation/categories.ts
- src/components/sidebar-navigation/sections.ts
- src/data/bos-components.ts
- src/pages/contact-us.tsx
Closes: https://github.com/near/near-discovery/issues/1064
- Point `/contact-us` to new Contact Us page
Part 1: https://github.com/near/near-discovery-components/pull/760
> Contact Us Page (2 of 2)

- public/push-notifications.js
This PR makes changes to push notifications, namely adding a link to the content of the notification
Closes https://github.com/near/near-discovery/issues/1007
> feat: use `actionAtBlockHeight` to generate link for push notification

- src/pages/s/[urlShareIndicator].tsx
companion post to https://github.com/near/near-discovery-components/pull/798 which is needed in order for shared urls to work. (links from action buttons)
> feat: update shared url to handle reposts

- next.config.js
add subdirectory redirect to airtable form for audit program 
Was related to ISR-197 but Erik pointed me to this repo. 
After reading on `permanent` true vs false, true seemed better as this is not likely something that will change frequently.
> add subdirectory redirect to airtable form for audit program

- src/pages/[componentAccountId]/widget/[componentName].tsx
Closes: https://github.com/near/near-discovery/issues/1134
> Adding back metadata SSR logic when viewing a component page

- src/components/vm/VmInitializer.tsx
Closes https://github.com/near/near-discovery/issues/1158
> update the custom `Link` component for functionality parity with near.social

- src/components/sidebar-navigation/styles.ts
Addresses #1208 by making login button violet
> Change login button color

- next.config.js
Updating the DNS to correctly reflect our project. Just updating the name.
> update dns from audit to assessment

- .env.example
- src/components/sidebar-navigation/Sidebar.tsx
- src/hooks/useEvents.ts
- src/hooks/useGoogleEvents.ts
- src/hooks/useLumaEvents.ts
- src/pages/events.tsx
- src/pages/index.tsx
- src/utils/config.ts
- src/utils/events.ts
- src/utils/types.ts
Adds aggregated events page.
closes https://github.com/near/near-discovery/issues/1252
@race-of-sloths
> feat: add events page

- package.json
- pnpm-lock.yaml
- src/components/CookiePrompt.tsx
- src/components/research-form-wizard/ResearchFormWizard.tsx
- src/components/vm/VmInitializer.tsx
- src/hooks/useResearchWizardEvents.tsx
- src/pages/_app.tsx
Had to fix a few ESLint errors that snuck through in a previous PR.
> Upgrade UI library to 1.0.0

- next.config.js
- src/components/NTFImage.tsx
- src/components/tools/Linkdrops/CreateNFTDrop.tsx
- src/components/tools/Linkdrops/CreateTokenDrop.tsx
- src/components/tools/Linkdrops/index.tsx
- src/hooks/useNFT.ts
> feat: add NFTs for linkdrops

- src/components/CookiePrompt.tsx
- src/pages/cookies/details.tsx
- src/pages/cookies/index.tsx
- src/styles/globals.css
Vm cookie was replaced by native for the app
> feat: vm cookie was replaced by native for the app

- src/pages/index.tsx
> fix(navbar): correct newletter bar issue on mobile

- src/components/scrollToTop.tsx
- src/config.ts
- src/pages/api/newsletter/subscribe.ts
- src/pages/newsletter.tsx
- fixes subscription form
- fixes visual issue with chat bubble overlaying `scroll to top`
> fix: subscribe form

- .env.example
- package.json
- pnpm-lock.yaml
- src/config.ts
- src/pages/cookies/details.tsx
- src/styles/globals.css
- src/utils/types.ts
remove unused dep
unblocks #1381
> chore: remove idos dep

- next.config.js
Remove near social redirect. regarding bug bounty `NEAR-251 ` submission.
> remove near social redirect

- src/components/sidebar-navigation/Sidebar.tsx
removes sidebar item `web3 architectures`
> chore: remove sidebar item

- src/styles/globals.css
Hiding fast auth login since the endpoint is not responding
> chore: hide fast auth

- src/components/sidebar-navigation/Sidebar.tsx
- src/pages/faucet.tsx
Created a small page that uses our `contract-helper` to create an account and delete it to emulate a faucet service
> Added Faucet
